/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Visualization
{
    public class InteractiveMarkerInit : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "visualization_msgs/InteractiveMarkerInit";

        //  Identifying string. Must be unique in the topic namespace
        //  that this server works on.
        public string server_id;
        //  Sequence number.
        //  The client will use this to detect if it has missed a subsequent
        //  update.  Every update message will have the same sequence number as
        //  an init message.  Clients will likely want to unsubscribe from the
        //  init topic after a successful initialization to avoid receiving
        //  duplicate data.
        public ulong seq_num;
        //  All markers.
        public InteractiveMarker[] markers;

        public InteractiveMarkerInit()
        {
            this.server_id = "";
            this.seq_num = 0;
            this.markers = new InteractiveMarker[0];
        }

        public InteractiveMarkerInit(string server_id, ulong seq_num, InteractiveMarker[] markers)
        {
            this.server_id = server_id;
            this.seq_num = seq_num;
            this.markers = markers;
        }
    }
}
