/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Visualization
{
    public class InteractiveMarkerPose : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "visualization_msgs/InteractiveMarkerPose";

        //  Time/frame info.
        public Header header;
        //  Initial pose. Also, defines the pivot point for rotations.
        public Pose pose;
        //  Identifying string. Must be globally unique in
        //  the topic that this message is sent through.
        public string name;

        public InteractiveMarkerPose()
        {
            this.header = new Header();
            this.pose = new Pose();
            this.name = "";
        }

        public InteractiveMarkerPose(Header header, Pose pose, string name)
        {
            this.header = header;
            this.pose = pose;
            this.name = name;
        }
    }
}
